### PR TITLE
Define major modes.

### PR DESCRIPTION
**Pull request by seagle0128**
1. Define major-modes (derived from special-mode): mingus-help-mode, mingus-playlist-mode, mingus-browse-mode and mingus-burn-mode.
2. Define keymaps accordingly.
3. Remove mingus-playlist-hooks.
4. Also address #42.
5. Other minor fixes.

### CODE REVIEW

**Comment by seagle0128** [comment]
@pft Please review and merge. Thanks!

**Comment by seagle0128** [comment]
Hi @pft  any update for this PR?

BTW, it seems you are pretty busy. I'd like maintain this great package if you agree.

**Comment by pft** [comment]
Yes, sorry, I am quite busy between work and private life. And not using mingus myself that much anymore currently.

Your changes seem well thought out, but I lack the time to review them properly and merge them with confidence.

So unless anyone objects,  I can add you as a collaborator so you can co-maintain the package.

**Comment by seagle0128** [comment]
Thanks, @pft ! I am using mingus everyday, so I think I can continue maintaining this great package!

**Comment by pft** [comment]
Awesome @seagle0128, I hate to see this child of mine go to waste.

**Pull request merged**
